
#ifndef RVIZ_DEFAULT_PLUGIN_EXPORT_H
#define RVIZ_DEFAULT_PLUGIN_EXPORT_H

#ifdef RVIZ_DEFAULT_PLUGIN_STATIC_DEFINE
#  define RVIZ_DEFAULT_PLUGIN_EXPORT
#  define RVIZ_DEFAULT_PLUGIN_NO_EXPORT
#else
#  ifndef RVIZ_DEFAULT_PLUGIN_EXPORT
#    ifdef rviz_default_plugin_EXPORTS
        /* We are building this library */
#      define RVIZ_DEFAULT_PLUGIN_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define RVIZ_DEFAULT_PLUGIN_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef RVIZ_DEFAULT_PLUGIN_NO_EXPORT
#    define RVIZ_DEFAULT_PLUGIN_NO_EXPORT 
#  endif
#endif

#ifndef RVIZ_DEFAULT_PLUGIN_DEPRECATED
#  define RVIZ_DEFAULT_PLUGIN_DEPRECATED __declspec(deprecated)
#endif

#ifndef RVIZ_DEFAULT_PLUGIN_DEPRECATED_EXPORT
#  define RVIZ_DEFAULT_PLUGIN_DEPRECATED_EXPORT RVIZ_DEFAULT_PLUGIN_EXPORT RVIZ_DEFAULT_PLUGIN_DEPRECATED
#endif

#ifndef RVIZ_DEFAULT_PLUGIN_DEPRECATED_NO_EXPORT
#  define RVIZ_DEFAULT_PLUGIN_DEPRECATED_NO_EXPORT RVIZ_DEFAULT_PLUGIN_NO_EXPORT RVIZ_DEFAULT_PLUGIN_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef RVIZ_DEFAULT_PLUGIN_NO_DEPRECATED
#    define RVIZ_DEFAULT_PLUGIN_NO_DEPRECATED
#  endif
#endif

#endif /* RVIZ_DEFAULT_PLUGIN_EXPORT_H */
